---

dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: master
    image: registry.access.redhat.com/ubi8/ubi-init
    networks:
      - name: "red_cluster"      
    hostname: master
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    capabilities:
      - SYS_ADMIN
    command: "/usr/sbin/init"
    privileged: true
    pre_build_image: true
  - name: nodo1
    image: registry.access.redhat.com/ubi8/ubi-init
    networks:
      - name: "red_cluster"      
    hostname: nodo1
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    capabilities:
      - SYS_ADMIN
    command: "/usr/sbin/init"
    privileged: true
    pre_build_image: true
  - name: nodo2
    image: registry.access.redhat.com/ubi8/ubi-init
    networks:
      - name: "red_cluster"      
    hostname: nodo2
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    capabilities:
      - SYS_ADMIN
    command: "/usr/sbin/init"
    privileged: true
    pre_build_image: true    
provisioner:
  name: ansible  
verifier:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint .

...