version: '3.7'
services:
  db:
    image: mysql
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - "3306:3306"  
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      update_config:
        delay: 10s
        parallelism: 2
        failure_action: continue
        monitor: 60s      

  wordpress:
    image: wordpress
    environment:
      MYSQL_PASSWORD: 123456
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_HOST: db    
    ports:
      - "80:80"
    depends_on:
      - db    
    volumes: 
      - wordpress:/var/www/html/
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
      update_config:
        delay: 10s
        parallelism: 2
        failure_action: continue
        monitor: 60s      

volumes:
  mysql:
  wordpress:        